require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'JohnnyClientRnRev2' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'JohnnyClientRnRev2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.75.0' })

  post_install do |installer|
    react_native_post_install(installer)

    # Ref : https://zenn.dev/myb/articles/4b1dd3821703aa2ac95b#pods%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AEbuild-settings%E3%82%92%E8%A8%AD%E5%AE%9A
    installer.pods_project.build_configurations.each do |build_configuration|
      build_configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'No'
    end
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.xcconfigs.each do |config_name, config_file|
        config_file.attributes['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] ='arm64'
        config_file.save_as(aggregate_target.xcconfig_path(config_name))
      end
    end

    # Ref : https://qiita.com/mk2/items/a087a3556116ff16afa6
    installer.pods_project.build_configurations.each do |build_configuration|
      build_configuration.build_settings['ONLY_ACTIVE_ARCH'] = 'No'
      build_configuration.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
      build_configuration.build_settings["EXCLUDED_ARCHS"] = "armv7"
    end
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.xcconfigs.each do |config_name, config_file|
        config_file.attributes['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] ='arm64 i386'
        config_file.attributes['EXCLUDED_ARCHS'] ='armv7'
        config_file.save_as(aggregate_target.xcconfig_path(config_name))
      end
    end
  end
end